// This file is auto-generated by @hey-api/openapi-ts

export type AuditAction = 'CREATE' | 'UPDATE' | 'DELETE';

/**
 * Public schema for audit log with ID
 */
export type AuditLogPublic = {
    table_name: string;
    record_id: string;
    action: AuditAction;
    old_values?: ({
    [key: string]: unknown;
} | null);
    new_values?: ({
    [key: string]: unknown;
} | null);
    changed_fields?: (Array<(string)> | null);
    user_id?: (string | null);
    timestamp: string;
    ip_address?: (string | null);
    user_agent?: (string | null);
    session_id?: (string | null);
    additional_info?: ({
    [key: string]: unknown;
} | null);
    id: string;
};

/**
 * Public schema for list of audit logs
 */
export type AuditLogsPublic = {
    data: Array<AuditLogPublic>;
    count: number;
};

export type BaseResponse_list_str__ = {
    /**
     * HTTP status code (200, 201, 400, 404, etc.)
     */
    code: number;
    /**
     * Human-readable message describing the operation result
     */
    message: string;
    /**
     * The actual response data. Type varies by endpoint. Can be null for update/delete operations.
     */
    data?: (Array<(string)> | null);
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type Body_upload_upload_files = {
    /**
     * Multiple files to upload
     */
    files: Array<((Blob | File))>;
};

export type Body_upload_upload_files_to_b2 = {
    /**
     * Multiple files to upload
     */
    files: Array<((Blob | File))>;
};

export type Body_upload_upload_files_to_s3 = {
    /**
     * Multiple files to upload
     */
    files: Array<((Blob | File))>;
};

/**
 * Request schema for Google OAuth authentication
 */
export type GoogleAuthRequest = {
    /**
     * Authorization code from Google OAuth
     */
    code: string;
};

/**
 * Response schema for Google OAuth authentication
 */
export type GoogleAuthResponse = {
    access_token: string;
    token_type?: string;
    user: UserPublic;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

/**
 * Generic message response schema.
 */
export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    google_id?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    google_id?: (string | null);
    id: string;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    google_id?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type AuditLogsGetAuditLogsData = {
    action?: (AuditAction | null);
    limit?: number;
    recordId?: (string | null);
    skip?: number;
    tableName?: (string | null);
    userId?: (string | null);
};

export type AuditLogsGetAuditLogsResponse = (AuditLogsPublic);

export type AuditLogsGetAuditLogData = {
    auditLogId: string;
};

export type AuditLogsGetAuditLogResponse = (AuditLogPublic);

export type AuditLogsGetRecordHistoryData = {
    limit?: number;
    recordId: string;
    skip?: number;
    tableName: string;
};

export type AuditLogsGetRecordHistoryResponse = (AuditLogsPublic);

export type AuditLogsGetUserAuditLogsData = {
    limit?: number;
    skip?: number;
    userId: string;
};

export type AuditLogsGetUserAuditLogsResponse = (AuditLogsPublic);

export type FileGetSignedUrlData = {
    /**
     * Number of days until the signed URL expires
     */
    expirationDays?: number;
    /**
     * Public GCS URL to convert to signed URL
     */
    url: string;
};

export type FileGetB2SignedUrlData = {
    /**
     * Number of hours until the presigned URL expires
     */
    expirationHours?: number;
    /**
     * Public B2 URL to convert to presigned URL
     */
    url: string;
};

export type FileGetS3SignedUrlData = {
    /**
     * Number of hours until the presigned URL expires
     */
    expirationHours?: number;
    /**
     * Public S3 URL to convert to presigned URL
     */
    url: string;
};

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type OauthGoogleLoginData = {
    requestBody: GoogleAuthRequest;
};

export type OauthGoogleLoginResponse = (GoogleAuthResponse);

export type PrivateCreateUserPrivateData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserPrivateResponse = (UserPublic);

export type UploadUploadFilesData = {
    formData: Body_upload_upload_files;
};

export type UploadUploadFilesResponse = (BaseResponse_list_str__);

export type UploadUploadFilesToB2Data = {
    formData: Body_upload_upload_files_to_b2;
};

export type UploadUploadFilesToB2Response = (BaseResponse_list_str__);

export type UploadUploadFilesToS3Data = {
    formData: Body_upload_upload_files_to_s3;
};

export type UploadUploadFilesToS3Response = (BaseResponse_list_str__);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);