"""Add chat tables for rooms, members, and messages

Revision ID: b978926ae163
Revises: bee8a8a646e4
Create Date: 2025-11-06 12:45:12.451111

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b978926ae163'
down_revision = 'bee8a8a646e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_room',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_room_name'), 'chat_room', ['name'], unique=False)
    op.create_table('chat_message',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('room_id', sa.Uuid(), nullable=True),
    sa.Column('sender_id', sa.Uuid(), nullable=False),
    sa.Column('recipient_id', sa.Uuid(), nullable=True),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(length=4000), nullable=False),
    sa.Column('message_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['chat_room.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_message_created_at'), 'chat_message', ['created_at'], unique=False)
    op.create_index(op.f('ix_chat_message_recipient_id'), 'chat_message', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_chat_message_room_id'), 'chat_message', ['room_id'], unique=False)
    op.create_index(op.f('ix_chat_message_sender_id'), 'chat_message', ['sender_id'], unique=False)
    op.create_table('chat_room_member',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('room_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['chat_room.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_room_member_room_id'), 'chat_room_member', ['room_id'], unique=False)
    op.create_index(op.f('ix_chat_room_member_user_id'), 'chat_room_member', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_room_member_user_id'), table_name='chat_room_member')
    op.drop_index(op.f('ix_chat_room_member_room_id'), table_name='chat_room_member')
    op.drop_table('chat_room_member')
    op.drop_index(op.f('ix_chat_message_sender_id'), table_name='chat_message')
    op.drop_index(op.f('ix_chat_message_room_id'), table_name='chat_message')
    op.drop_index(op.f('ix_chat_message_recipient_id'), table_name='chat_message')
    op.drop_index(op.f('ix_chat_message_created_at'), table_name='chat_message')
    op.drop_table('chat_message')
    op.drop_index(op.f('ix_chat_room_name'), table_name='chat_room')
    op.drop_table('chat_room')
    # ### end Alembic commands ###
