"""add sites moduls

Revision ID: c8bd78045e06
Revises: ce02597ab6e2
Create Date: 2025-11-06 08:40:56.435094

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c8bd78045e06'
down_revision = 'ce02597ab6e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('domain', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('frontend_domain', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_domain'), 'site', ['domain'], unique=True)
    op.create_index(op.f('ix_site_is_default'), 'site', ['is_default'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_site_is_default'), table_name='site')
    op.drop_index(op.f('ix_site_domain'), table_name='site')
    op.drop_table('site')
    # ### end Alembic commands ###
